diary/urls.py
 
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
     
    path('admin/', admin.site.urls),
    path('', include('h_w_list.urls')),
    path('sendhomework/', include('h_w.urls')),
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

h_w/urls.py
from django.conf import settings
from django.urls import path
from . import views
from .views import H_W_Image_SendCreate
from django.conf.urls.static import static

app_name = 'h_w'
urlpatterns = [
    path('', views.h_w, name = 'h_w'),
    path('image/', H_W_Image_SendCreate.as_view()),
     path('image/',  views.h_w_i, name = 'h_w_i')
    
    

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

h_w_list/urls.py
from django.urls import path
from . import views

app_name = 'h_w_list'
urlpatterns = [
    path('', views.h_w_list, name = 'h_w_list'),
    

    

]

h_w/models.py
from django.db import models

class H_W_Send(models.Model):
     h_w_send_lesson = models.CharField('Предмет', max_length = 100)
     h_w_send_name = models.CharField('ФИО', max_length = 100)
     h_w_send_text = models.TextField('Текст задания')
     

     def __str__(self):
           return self.h_w_send_name
     
     


     
     class Meta:
          verbose_name = 'Отправленное Д/З'
          verbose_name_plural = 'Отправленные Д/З'


class H_W_Image_Send(models.Model):
     h_w_send_image_lesson = models.CharField('Предмет', max_length = 100)
     h_w_send_image_name = models.CharField('ФИО', max_length = 100)
     h_w_send_image_text = models.CharField('Текст задания', max_length = 100)
     h_w_send_image = models.ImageField('Фото задания', upload_to='images/')

     

     def __str__(self):
           return self.h_w_send_image_name
     
     


     
     class Meta:
          verbose_name = 'Отправленное Д/З в виде фото'
          verbose_name_plural = 'Отправленные Д/З в виде фото'

h_w_list/models.py
import datetime
from tabnanny import verbose
from django.db import models

from django.utils import timezone

class H_W(models.Model):
     h_w_title = models.CharField('Предмет', max_length = 200)
     h_w_text = models.TextField('Текст')
     pub_date = models.DateTimeField('Число на которое задано:')

     def __str__(self):
           return self.h_w_title
     
     def was_published_recently(self):
           return self.pub_date < timezone.now()


     
     class Meta:
          verbose_name = 'Д/З'
          verbose_name_plural = 'Д/З'
         

h_w/forms.py
from .models import H_W_Send, H_W_Image_Send
from django.forms import ModelForm, TextInput, Textarea,ImageField



class H_W_Send_Form(ModelForm):
    class Meta:
        model = H_W_Send
        fields = ["h_w_send_name", "h_w_send_lesson", "h_w_send_text"]
        widgets = {
            "h_w_send_name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите имя'

        }),
            "h_w_send_lesson": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите предмет'

        }),
            "h_w_send_text": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст'

        })
        }


class H_W_Image_SendForm(ModelForm):

    class Meta:
        model = H_W_Image_Send
        fields = '__all__'   
        widgets = {
            "h_w_send_image_name": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите имя'

        }),
            "h_w_send_image_lesson": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите предмет'

        }),
            "h_w_send_image_text": TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Введите текст'

        })
        }  
                


        
        

h_w/views.py
from django.shortcuts import render
from .forms import H_W_Send_Form, H_W_Image_SendForm
from django.views.generic import CreateView
from .models import H_W_Image_Send
from django.views.generic import CreateView

def h_w(request):
    error = ''
    if request.method == 'POST':
        form = H_W_Send_Form(request.POST)
        if form.is_valid():
            form.save()
            
        else:
            error = 'Форма неверна!'

    
    
    form = H_W_Send_Form() 
    context = {
        'form': form
    }
    return render(request, 'h_w/h_w.html', context)


def h_w_i(request):
    pass


class H_W_Image_SendCreate(CreateView):
    
    model = H_W_Image_Send
    
    form_class = H_W_Image_SendForm
    
    extra_context = {'books': H_W_Image_Send.objects.all()}
    
    template_name = 'h_w/h_w_i.html'
    
    success_url = '/'

h_w_list/views.py
from django.shortcuts import render


from .models import H_W

def h_w_list(request):
    latest_articles_list = H_W.objects.order_by('-pub_date')[:200]
    return render(request, 'h_w_list/h_w_list.html',  {'latest_articles_list':latest_articles_list})





    
    

h_w/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
          <span class="fs-1">Дневник </span>
        </a>
  
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'h_w:h_w'  %}">Отправить Д/З</a>
          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'h_w:h_w_i'  %}">Отправить Д/З фото</a>
          
          
        </nav>
      </div>
    {% block content %}{% endblock%}
</body>
</html>

h_w/templates/h_w/h_w.html
{% extends "base.html" %}

{% block title %}Отправить Д/З{% endblock %}

{% block content %}
    <h2>Отправить Д/З</h2>
    <form method="post" >
        {% csrf_token %}
        {{form.h_w_send_name}} <br>
        {{ form.h_w_send_lesson}} <br>
        {{form.h_w_send_text}} <br>
        <button type="submit" class="btn btn-success">Отправить </button>
        <span>{{ error }}</span>
    </form>
{% endblock %}

h_w/templates/h_w/h_w_i.html
{% extends "base.html" %}

{% block title %}Отправить Д/З в виде фото{% endblock %}

{% block content %}
    <h2>Отправить Д/З</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Отправить </button>
    </form>
    
{% endblock %}

h_w_list/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
</head>
<body>
    
    <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
          <span class="fs-1">Дневник </span>
        </a>
  
        <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'h_w:h_w'  %}">Отправить Д/З</a>
          <a class="me-3 py-2 text-dark text-decoration-none" href="{% url 'h_w:h_w_i'  %}">Отправить Д/З фото</a>

          
          
          
        </nav>
      </div>
    {% block content %}{% endblock%}
</body>
</html>

h_w_list/templates/h_w_list/h_w_list.html
{% extends "base.html" %}

{% block title %}Дневник{% endblock %}

{% block content %}
<h2>Задания на дом:
</h2><br>
<br>

{% if latest_articles_list %}
    {% for a in latest_articles_list %}
        <div  class="alert alert-dark" role="alert mt-2">
            <h3> {{a.h_w_title}} </h3>
            <p>{{a.h_w_text}}</p>
            {% if a.was_published_recently %}
                Задание скорее всего истекло, сообщите админам чтобы удалили!<br>
                <em>Было задано на {{a.pub_date}}</em>
            {% else %}
               <em>Задано на {{a.pub_date}}</em>
            {% endif %}
        </div>
        
    {% endfor %}

{% else %}
    <h2>Домашних заданий на неделю нет, отдыхай!</h2>
{% endif %}
    

{% endblock %}